import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:tasks/bloc/theme/dynamic_color.dart';
import 'package:tasks/presentation/pages/settings/settings_page_widgets.dart';
import '../../../bloc/theme/theme_cubit.dart';

class SettingsPageContent extends StatelessWidget {
  final String title;
  const SettingsPageContent(this.title, {super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(title)),
      body: Padding(
        padding: const EdgeInsets.only(left: 14, right: 10),
        child: Column(
          spacing: 18,
          children: [
            BlocBuilder<ThemeCubit, ThemeMode>(
              builder: (context, themeMode) {
                return appSettings(
                  icon: Icons.water_drop,
                  title: "Follow system' dark theme",
                  descreption:
                      "Automatically switch to dark theme based on system settings",
                  value: themeMode == ThemeMode.system,
                  onChanged: (enabled) {
                    context.read<ThemeCubit>().setSystemMode(enabled);
                  },
                );
              },
            ),
            BlocBuilder<DynamicColorCubit, bool>(
              builder: (context, useDynamic) {
                return appSettings(
                  icon: Icons.color_lens,
                  title: "System color theme",
                  descreption:
                      "Use a color theme generated by system based on the current wallpaper",
                  value: useDynamic,
                  onChanged: (value) {
                    context.read<DynamicColorCubit>().setDynamicColor(value);
                  },
                );
              },
            ),
          ],
        ),
      ),
    );
  }
}
